//A Jenkinsfile for start
podTemplate(label: 'my-pod',
  containers:[
    containerTemplate(name: 'compiler', image:'golang:1.8.3',ttyEnabled: true, command: 'cat', envVars:[
        containerEnvVar(key: 'BUILD_NUMBER', value: env.BUILD_NUMBER),
        containerEnvVar(key: 'BUILD_ID', value: env.BUILD_ID),
        containerEnvVar(key: 'BUILD_URL', value: env.BUILD_URL),
        containerEnvVar(key: 'BUILD_TAG', value: env.BUILD_TAG),
        containerEnvVar(key: 'JOB_NAME', value: env.JOB_NAME)
      ],
    ),
    containerTemplate(name: 'citools', image:'zhiminwen/citools',ttyEnabled: true, command: 'cat', envVars:[
        // these env is only available in container template? podEnvVar deosn't work?!
        containerEnvVar(key: 'BUILD_NUMBER', value: env.BUILD_NUMBER),
        containerEnvVar(key: 'BUILD_ID', value: env.BUILD_ID),
        containerEnvVar(key: 'BUILD_URL', value: env.BUILD_URL),
        containerEnvVar(key: 'BUILD_TAG', value: env.BUILD_TAG),
        containerEnvVar(key: 'JOB_NAME', value: env.JOB_NAME)
      ],
    )
  ],
  volumes: [
    //for docker to work
    hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock')
  ]
){
  node('my-pod') {
    stage('clone git repo'){
      checkout scm

      container('compiler'){
       stage('Compile and Build'){
         sh("echo compile")
       }
      }

      container('citools'){
        stage('Docker Build'){
          // sleep 3600
          sh "echo build docker image"
          // sh "rake -f build.rb docker:01_build_image docker:02_push_to_ICp_registry"
        }

        stage('Deploy into k8s'){
          sh "echo rollout to k8s"
          // sh "rake -f build.rb k8s:01_deploy_to_k8s"
        }
      }
    }
  }
}
